      ******************************************************************
      * Author: Stanley Zhong
      * Date: Updated 5/11/2020
      * Purpose: Read numbers from a file and print them
      *          Numbers generated by FILE-WRITER.cbl
      * Tectonics: cobc
      ******************************************************************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. FILE-ECHO.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
           FILE-CONTROL.
               SELECT ARRAY-FILE ASSIGN TO WS-FILE-NAME.

       DATA DIVISION.
       FILE SECTION.
           FD ARRAY-FILE.
           01 ARRAY-DATA.
               05 STUFF-STUFF PIC 9(10).
       WORKING-STORAGE SECTION.
           01 WS-FILE-NAME PIC X(100).
           01 WS-DATA.
               05 WS-NUMBER PIC 9(10).
           01 WS-EOF PIC A(3) VALUE "NO".
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           DISPLAY "Enter file path for the file you want to read:"
           ACCEPT WS-FILE-NAME

           OPEN INPUT ARRAY-FILE
           PERFORM UNTIL WS-EOF="YES"
               READ ARRAY-FILE INTO WS-DATA
                   AT END MOVE "YES" TO WS-EOF
                   NOT AT END DISPLAY WS-NUMBER
               END-READ
           END-PERFORM

           CLOSE ARRAY-FILE

           STOP RUN.
       END PROGRAM FILE-ECHO.
